name: Build multiplatform debug

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
    steps:
      - name: Project setup
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Install deps windows
        if: ${{matrix.os == 'windows-latest'}}
        run: choco install openssl

      - name: Install deps linux
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: sudo apt-get install -y libssl-dev

      - name: Build
        run: |
          cd build
          openssl version -a
          cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .


