name: Linux build

on:
  workflow_dispatch:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cpp_compiler: [gcc,clang]
    steps:
      - name: Clone branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - name: Dependencies setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake openssl libssl-dev
      - name: Build
        run: |
          cd build
          /usr/bin/cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DDO_TEST=ON .. && /usr/bin/cmake --build .

