name: Test build

on:
  workflow_dispatch:
  
jobs:
  linux-build:
    uses: ./.github/workflows/linux-test-build.yml
  windows-build:
    needs: [linux-build]
    uses: ./.github/workflows/windows-test-build.yml
  test-build:
    needs: [linux-build,windows-build]
    runs-on: ubuntu-latest
    steps:
      - run: true
